"""Add outbox events table

Revision ID: 11be27b7e1b4
Revises: 0746690a54ca
Create Date: 2026-08-06 22:02:31.683126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.outbox


# revision identifiers, used by Alembic.
revision: str = '11be27b7e1b4'
down_revision: Union[str, Sequence[str], None] = '0746690a54ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', app.core.outbox.JSONEncodedDict(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
