"""audit_fixes

Revision ID: 30d1e3db530b
Revises: 2873bb6cc642
Create Date: 2026-08-06 15:42:40.503697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d1e3db530b'
down_revision: Union[str, Sequence[str], None] = '2873bb6cc642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_favorite_session_photo', ['session_id', 'photo_id'])
        batch_op.create_unique_constraint('uq_favorite_user_photo', ['user_id', 'photo_id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_photo_id'), ['photo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_photo_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('uq_favorite_user_photo', type_='unique')
        batch_op.drop_constraint('uq_favorite_session_photo', type_='unique')

    # ### end Alembic commands ###
