"""Add failed_attempts and is_locked to OTPCode

Revision ID: 31eb99e37b7b
Revises: 11be27b7e1b4
Create Date: 2026-08-07 12:18:23.236930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eb99e37b7b'
down_revision: Union[str, Sequence[str], None] = '11be27b7e1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_column('is_locked')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
